### ISSUE TITLE
Success

### ISSUE THREAD

**Issue by FiberJW** [blakeembrey/code-challenge#2]
is there a success event or api for challenges?

**Comment by blakeembrey** [comment]
Hi @datwheat! I haven't worked on this project for a long time. What are you trying to do specifically?

**Comment by FiberJW** [comment]
I have a club that i'm starting and I want to find a way to create a leaderboard based on challenge completion. When a user completes it i want to write to a server or something

**Comment by blakeembrey** [comment]
Are you using this today? I'd love to help out however I can, but I'm not sure where to start 😄 Do you imagine it's some kind of plugin?

**Comment by FiberJW** [comment]
It's for next winter. All i need is to be able to use a callback when writing an exercise. like `.add('success', function() {})`

**Comment by blakeembrey** [comment]
If you're writing the challenge, couldn't you use `verify` and do the `success` handler there? Just curious.

**Comment by FiberJW** [comment]
like on the `assert.equal()` call?

**Comment by blakeembrey** [comment]
Afterwards, yes.

**Comment by FiberJW** [comment]
ah because assert throws an error if it's wrong

**Comment by blakeembrey** [comment]
Yes, in the same situation the there'd be no `success` event either?
